### ISSUE TITLE
I need help (Templated)

### ISSUE THREAD

**Issue by XenoEmblems** [XenoEmblems/AniRec#2]
CONTEXT

@bigtone1284 @williamfshaw @h4w5 @hari @drrobotmck

WHAT USER STORY YOU ARE WORKING ON:

I am working on the user story: "As a user I want to access the OMDB API by using a text box."

Right now I am trying to debug everything and then fix the GET route in the Movie Router to present a model. I want to make sure this works before I make views.

WHAT YOU ARE TRYING TO DO:

I am going through Nodemon server.js to debug each issue one by one until I can try to fix the GET route.

DETAILED DESCRIPTION OF THE BUG/ERROR:

This is all being done in js/routers/movie_router.js  search should be called by a search query (req.query) and then it would combine with the baseURL then the title, poster, .etc. Then the GET route should create a new model where I will then use the templates and views to use it. The problem is that there are a lot of errors including this one. 

`21 Apr 11:07:53 - [nodemon] app crashed - waiting for file changes before starting...
21 Apr 11:08:18 - [nodemon] restarting due to changes...
21 Apr 11:08:18 - [nodemon] starting `node server.js`
body-parser deprecated bodyParser: use individual json/urlencoded middlewares public/js/routers/movie_router.js:16:10
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:85:29
body-parser deprecated bodyParser: use individual json/urlencoded middlewares public/js/routers/user_router.js:14:10
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option public/js/routers/user_router.js:18:9
body-parser deprecated bodyParser: use individual json/urlencoded middlewares server.js:18:10
/Users/ericxavierdoyle/SoloProject/node_modules/express/lib/router/index.js:446
      throw new TypeError('Router.use() requires middleware function but got a
            ^
TypeError: Router.use() requires middleware function but got a Object
    at Function.<anonymous> (/Users/ericxavierdoyle/SoloProject/node_modules/express/lib/router/index.js:446:13)
    at Array.forEach (native)
    at Function.use (/Users/ericxavierdoyle/SoloProject/node_modules/express/lib/router/index.js:444:13)
    at EventEmitter.<anonymous> (/Users/ericxavierdoyle/SoloProject/node_modules/express/lib/application.js:216:21)
    at Array.forEach (native)
    at EventEmitter.use (/Users/ericxavierdoyle/SoloProject/node_modules/express/lib/application.js:213:7)
    at Object.<anonymous> (/Users/ericxavierdoyle/SoloProject/server.js:21:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
21 Apr 11:08:19 - [nodemon] app crashed - waiting for file changes before starting...`

WHAT I'VE TRIED

I have been going through Nodemon and editing pieces of code specifically where the models are. It's weird that for example that nodemon goes through when on line 8 on server.js 
`movieRouter      = require('./public/js/routers/movie_router.js'),`
And in movie_router.js on line 7 `models           = require('../../../models'),`
But I just left it alone for now until I can get no errors and now I am stuck in a rut.
QUESTION

What is the best way to attempt to clear these errors. I know this is a direct question but I have been plugging at this for a few hours and I am stuck. 

Sincerely,
Eric Doyle

**Comment by bigtone1284** [comment]
taken

**Comment by bigtone1284** [comment]
@XenoEmblems please close this issue :)

**Comment by bigtone1284** [comment]
@XenoEmblems Please close this issue.
