### ISSUE TITLE
Why don't I see any of the templates?

### ISSUE THREAD

**Issue by XenoEmblems** [XenoEmblems/AniRec#3]
@bigtone1284 @williamfshaw @h4w5 @hari @drrobotmck
CONTEXT: 
I just really want to sit with someone and work see why my templates and views aren't working. They are all set up but there could be a fundamental flaw that I am missing. I would like someone to catch what I missed.

What User Story You Are Working On:

I want all my views and templates to be able to be activated and seen on the front-end.

What Are You Trying To Do:

I relooked at my Models/Collections/Views/Templates and debugged various things via the terminal and now I don't have much leeway on what to fix next. 

Detailed Description of the Bug/Error/What I've Tried

I put buttons in the templates that should call a click event in the views to render each of them. Login/Sign, Search, User Modal, and All Users. One thing that I am going try later but I would appreciate help is that when I click the User button it will go to the modal. I would check my previous work but I am hungry right as I was typing this and I went to go eat.

Question:

How can I show templates/views and my modal to the front-end? 

Sincerely,
Eric Doyle

**Comment by bigtone1284** [comment]
taken @XenoEmblems where are you working?  I can help.

**Comment by bigtone1284** [comment]
taken.
@harimohanraj89 @DrRobotmck @DrRobotmck

**Comment by XenoEmblems** [comment]
I'm on the third floor in the back.

**Comment by bigtone1284** [comment]
Talked with @XenoEmblems, will tb later to see if solution worked after implementing it.

**Comment by bigtone1284** [comment]
@XenoEmblems please update where you are at on here :+1: )

**Comment by XenoEmblems** [comment]
Search Template and View is now visible. (With an issue but I can fix it myself) But now thought all three of my user views/templates aren't working and returning the error. ( App.user.toJSON is not a function ) from line 18 ( this.$el.append( this.usermodal( App.user.toJSON() ) ); )

**Comment by bigtone1284** [comment]
@XenoEmblems update me later! :+1:
